#### this file contains BTC/USD data from "2015-10-8 13:40" to "2021-07-22 00:04:00"

data  downloaded from https://www.cryptodatadownload.com/data/gemini/

PS: volume is btc unit

#### summary of this file

1. download files

2. concat our work and generate df [datatime, closeprice, volume, returns% (close price), volume, volatility of 10m,30m,1h,3h,6h,12h,24h(not for volatility)]

and save as btc_everything.csv


In [1]:
import pandas as pd
import ssl #for changing a setting of http cert when downloading data
import numpy as np
from datetime import datetime,timedelta #sth related to date

PS: depends on how many threads you can start in you cpu

In [2]:
# define a function, args include csv name defined by you and link for download/filepath
def download_minute_data(name, filepath_or_link):
    '''
    input name and link in str format, to generate csv file #this line is instruction
    '''
    ssl._create_default_https_context = ssl._create_unverified_context #some changes related to HTTPS cert
    df = pd.read_csv(filepath_or_link, skiprows=1)  #create df from path # skip row 1 because row 1 is not related
    print(df.head()) #just to check the start and end time, to make sure i am downloading the correct thing
    print(df.tail())
    df.to_csv(name+'.csv') #save

#### if you have the files in the same folder already, dont run again
### <mark style="background-color: yellow">PS: running the last line (2021) will have a very high chance of changing the newest data time, csv from the 2021 link is continuously updating. so therefore, i will only provide the code with # here but not run it. instead, i will read the files directly from the same folder</mark>

if you want to try whether this function is working properly, you can try 2015-2020. but highly recommend not to download 2021 data

In [3]:
# PS: need internet connection, download online

# download_minute_data('2015min','https://www.cryptodatadownload.com/cdd/gemini_BTCUSD_2015_1min.csv')
# download_minute_data('2016min','https://www.cryptodatadownload.com/cdd/gemini_BTCUSD_2016_1min.csv')
# download_minute_data('2017min','https://www.cryptodatadownload.com/cdd/gemini_BTCUSD_2017_1min.csv')
# download_minute_data('2018min','https://www.cryptodatadownload.com/cdd/gemini_BTCUSD_2018_1min.csv')
# download_minute_data('2019min','https://www.cryptodatadownload.com/cdd/gemini_BTCUSD_2019_1min.csv')
# download_minute_data('2020min','https://www.cryptodatadownload.com/cdd/gemini_BTCUSD_2020_1min.csv')
# download_minute_data('2021min','https://www.cryptodatadownload.com/cdd/gemini_BTCUSD_2021_1min.csv')

#### if you have already the files, start from here, above is for showing prof web scraping skills

In [4]:
# for if you have already the files, start from here
_2015min = pd.read_csv('2015min.csv')
_2016min = pd.read_csv('2016min.csv')
_2017min = pd.read_csv('2017min.csv')
_2018min = pd.read_csv('2018min.csv')
_2019min = pd.read_csv('2019min.csv')
_2020min = pd.read_csv('2020min.csv')
_2021min = pd.read_csv('2021min.csv')

In [5]:
# show prof. in this project, our newest data time is '2021-07-22 00:04:00' if dont change the attached csv given
_2021min.head()

Unnamed: 0  Unix Timestamp                 Date  Symbol      Open  \
0           0   1626912240000  2021-07-22 00:04:00  BTCUSD  31979.61   
1           1   1626912180000  2021-07-22 00:03:00  BTCUSD  31962.79   
2           2   1626912120000  2021-07-22 00:02:00  BTCUSD  32020.05   
3           3   1626912060000  2021-07-22 00:01:00  BTCUSD  32096.50   
4           4   1626912000000  2021-07-22 00:00:00  BTCUSD  32142.86   

       High       Low     Close    Volume  
0  32007.58  31974.32  31980.59  0.107347  
1  31979.61  31868.75  31979.61  2.634666  
2  32028.77  31946.06  31962.79  1.128569  
3  32096.50  32020.05  32020.05  1.401139  
4  32156.91  32096.50  32096.50  0.026117

In [6]:
# concat all csv 
# _1min means 1min interval
_1min = pd.concat([_2021min,_2020min,_2019min,_2018min,_2017min,_2016min,_2015min]) #concat into a big df with btc data of all years
_1min.to_csv('1min.csv') #save
_1min.reset_index(drop=True, inplace=True) #because concat from different files, so need to reset index
_1min.head()

Unnamed: 0  Unix Timestamp                 Date  Symbol      Open  \
0           0   1626912240000  2021-07-22 00:04:00  BTCUSD  31979.61   
1           1   1626912180000  2021-07-22 00:03:00  BTCUSD  31962.79   
2           2   1626912120000  2021-07-22 00:02:00  BTCUSD  32020.05   
3           3   1626912060000  2021-07-22 00:01:00  BTCUSD  32096.50   
4           4   1626912000000  2021-07-22 00:00:00  BTCUSD  32142.86   

       High       Low     Close    Volume  
0  32007.58  31974.32  31980.59  0.107347  
1  31979.61  31868.75  31979.61  2.634666  
2  32028.77  31946.06  31962.79  1.128569  
3  32096.50  32020.05  32020.05  1.401139  
4  32156.91  32096.50  32096.50  0.026117

In [7]:
btc_time_close_volume = _1min[['Date','Close','Volume']] #we only use date close volume, therefore extract these 3 columns only
btc_time_close_volume.reset_index(drop=True, inplace=True)  #reset index
btc_time_close_volume #check

Date     Close    Volume
0        2021-07-22 00:04:00  31980.59  0.107347
1        2021-07-22 00:03:00  31979.61  2.634666
2        2021-07-22 00:02:00  31962.79  1.128569
3        2021-07-22 00:01:00  32020.05  1.401139
4        2021-07-22 00:00:00  32096.50  0.026117
...                      ...       ...       ...
2938661  2015-10-08 13:44:00    242.96  0.033491
2938662  2015-10-08 13:43:00    242.96  0.010000
2938663  2015-10-08 13:42:00    242.95  0.000000
2938664  2015-10-08 13:41:00    242.95  0.001000
2938665  2015-10-08 13:40:00    242.50  0.050000

[2938666 rows x 3 columns]

In [8]:
btc_time_close_volume.to_csv('btc_time_close_volume.csv') #save #just regard this as a checkpoint

In [9]:
# time in min, used for slicing
_1d=24*60
_12h=12*60
_6h=6*60
_3h=3*60
_1h=60
_30m=30
_10m=10
_1m=1 #not for analyzing, but for the nan row, will see that below

In [10]:
asc_p=list(btc_time_close_volume['Close'])[::-1] #reverse the time order, more readable, asc = ascending
asc_p_arr = np.array(asc_p) #change to array first so is faster

In [11]:
def cal_returns(time, name): #_p is price #function used for calculating returns
    shift_p = asc_p_arr[time:] #shifted price list
    now_p = asc_p_arr[:len(asc_p)-time] #now price list
    return_list = np.multiply(np.divide(np.subtract(shift_p, now_p), now_p),100) #new-old/old*100% formula for returns
    return pd.DataFrame({'return% '+name : return_list}) #return df

In [12]:
#put together

# ~5sec
returns_df = pd.concat( #concat all returns column into one df first
    [
    cal_returns(_1m,'1m'),
    cal_returns(_10m,'10m'),
    cal_returns(_30m,'30m'),
    cal_returns(_1h,'1h'),
    cal_returns(_3h,'3h'),
    cal_returns(_6h,'6h'),
    cal_returns(_12h,'12h'),
    cal_returns(_1d,'1d'),
    ],
    axis=1
)


##### becareful, there is no any future price for the newest time, so the whole row is NaN
since it is the first row, it is automatically removed (see below cell).
so we need to add a row of zeros, to have same shape

for tackling the NaN rows, we will limit the newest tweet to '2021-07-22 00:03:00' (1d before), date before this time will not have NaN

In [13]:
# important
print(returns_df.shape,btc_time_close_volume.shape) #you can see the row difference is |1|

returns_df.tail(11)

(2938665, 8) (2938666, 3)


return% 1m  return% 10m  return% 30m  return% 1h  return% 3h  \
2938654    0.026618    -0.557327          NaN         NaN         NaN   
2938655   -0.127800    -0.580743          NaN         NaN         NaN   
2938656   -0.015781          NaN          NaN         NaN         NaN   
2938657   -0.027645          NaN          NaN         NaN         NaN   
2938658   -0.013546          NaN          NaN         NaN         NaN   
2938659    0.108602          NaN          NaN         NaN         NaN   
2938660   -0.144231          NaN          NaN         NaN         NaN   
2938661   -0.238188          NaN          NaN         NaN         NaN   
2938662   -0.178825          NaN          NaN         NaN         NaN   
2938663    0.052624          NaN          NaN         NaN         NaN   
2938664    0.003064          NaN          NaN         NaN         NaN   

         return% 6h  return% 12h  return% 1d  
2938654         NaN          NaN         NaN  
2938655         NaN          NaN         NaN  
2938656         NaN          NaN         NaN  
2938657         NaN          NaN         NaN  
2938658         NaN          NaN         NaN  
2938659         NaN          NaN         NaN  
2938660         NaN          NaN         NaN  
2938661         NaN          NaN         NaN  
2938662         NaN          NaN         NaN  
2938663         NaN          NaN         NaN  
2938664         NaN          NaN         NaN

In [14]:
#add one zero row at bottom
returns_df.loc[len(returns_df)] = 0
returns_df

return% 1m  return% 10m  return% 30m  return% 1h  return% 3h  \
0          0.185567     1.030928     0.824742    1.010309    0.824742   
1          0.000000     0.843795     0.637991    0.823215    0.637991   
2          0.004116     0.843795     0.637991    0.823215    0.637991   
3          0.000000     0.839644     0.633849    0.839644    0.633849   
4          0.000000     0.839644     0.633849    0.839644    0.633849   
...             ...          ...          ...         ...         ...   
2938661   -0.238188          NaN          NaN         NaN         NaN   
2938662   -0.178825          NaN          NaN         NaN         NaN   
2938663    0.052624          NaN          NaN         NaN         NaN   
2938664    0.003064          NaN          NaN         NaN         NaN   
2938665    0.000000     0.000000     0.000000    0.000000    0.000000   

         return% 6h  return% 12h  return% 1d  
0          0.618557     0.453608    0.618557  
1          0.432188     0.267545    0.432188  
2          0.432188     0.267545    0.432188  
3          0.428054     0.263418    0.428054  
4          0.428054     0.263418    0.428054  
...             ...          ...         ...  
2938661         NaN          NaN         NaN  
2938662         NaN          NaN         NaN  
2938663         NaN          NaN         NaN  
2938664         NaN          NaN         NaN  
2938665    0.000000     0.000000    0.000000  

[2938666 rows x 8 columns]

In [15]:
#reverse back

returns_df_back = returns_df[::-1]
returns_df_back.reset_index(drop=True, inplace=True)
returns_df_back

return% 1m  return% 10m  return% 30m  return% 1h  return% 3h  \
0          0.000000     0.000000     0.000000    0.000000    0.000000   
1          0.003064          NaN          NaN         NaN         NaN   
2          0.052624          NaN          NaN         NaN         NaN   
3         -0.178825          NaN          NaN         NaN         NaN   
4         -0.238188          NaN          NaN         NaN         NaN   
...             ...          ...          ...         ...         ...   
2938661    0.000000     0.839644     0.633849    0.839644    0.633849   
2938662    0.000000     0.839644     0.633849    0.839644    0.633849   
2938663    0.004116     0.843795     0.637991    0.823215    0.637991   
2938664    0.000000     0.843795     0.637991    0.823215    0.637991   
2938665    0.185567     1.030928     0.824742    1.010309    0.824742   

         return% 6h  return% 12h  return% 1d  
0          0.000000     0.000000    0.000000  
1               NaN          NaN         NaN  
2               NaN          NaN         NaN  
3               NaN          NaN         NaN  
4               NaN          NaN         NaN  
...             ...          ...         ...  
2938661    0.428054     0.263418    0.428054  
2938662    0.428054     0.263418    0.428054  
2938663    0.432188     0.267545    0.432188  
2938664    0.432188     0.267545    0.432188  
2938665    0.618557     0.453608    0.618557  

[2938666 rows x 8 columns]

In [16]:
# ~10s
#concat and save
btc_time_close_volume_ret = pd.concat([btc_time_close_volume, returns_df_back], axis=1)
# btc_time_close_volume_ret.to_csv('btc_time_close_volume_ret.csv')
btc_time_close_volume_ret

Date     Close    Volume  return% 1m  return% 10m  \
0        2021-07-22 00:04:00  31980.59  0.107347    0.000000     0.000000   
1        2021-07-22 00:03:00  31979.61  2.634666    0.003064          NaN   
2        2021-07-22 00:02:00  31962.79  1.128569    0.052624          NaN   
3        2021-07-22 00:01:00  32020.05  1.401139   -0.178825          NaN   
4        2021-07-22 00:00:00  32096.50  0.026117   -0.238188          NaN   
...                      ...       ...       ...         ...          ...   
2938661  2015-10-08 13:44:00    242.96  0.033491    0.000000     0.839644   
2938662  2015-10-08 13:43:00    242.96  0.010000    0.000000     0.839644   
2938663  2015-10-08 13:42:00    242.95  0.000000    0.004116     0.843795   
2938664  2015-10-08 13:41:00    242.95  0.001000    0.000000     0.843795   
2938665  2015-10-08 13:40:00    242.50  0.050000    0.185567     1.030928   

         return% 30m  return% 1h  return% 3h  return% 6h  return% 12h  \
0           0.000000    0.000000    0.000000    0.000000     0.000000   
1                NaN         NaN         NaN         NaN          NaN   
2                NaN         NaN         NaN         NaN          NaN   
3                NaN         NaN         NaN         NaN          NaN   
4                NaN         NaN         NaN         NaN          NaN   
...              ...         ...         ...         ...          ...   
2938661     0.633849    0.839644    0.633849    0.428054     0.263418   
2938662     0.633849    0.839644    0.633849    0.428054     0.263418   
2938663     0.637991    0.823215    0.637991    0.432188     0.267545   
2938664     0.637991    0.823215    0.637991    0.432188     0.267545   
2938665     0.824742    1.010309    0.824742    0.618557     0.453608   

         return% 1d  
0          0.000000  
1               NaN  
2               NaN  
3               NaN  
4               NaN  
...             ...  
2938661    0.428054  
2938662    0.428054  
2938663    0.432188  
2938664    0.432188  
2938665    0.618557  

[2938666 rows x 11 columns]

return part is finished

##### now start vol of diff time intervals

the steps are similar to return

In [17]:
asc_v_np=np.array(btc_time_close_volume['Volume'])[::-1] #reverse the time order, more readable, asc = ascending
#p is price, v is vol

In [18]:
#this cell just for demo, nothing related to btc
#we have taklked about this in presentation already

print(np.arange(10),end='\n\n')
testingtestingtesting = np.lib.stride_tricks.sliding_window_view(np.arange(10),5)
print(testingtestingtesting)
np.sum(testingtestingtesting ,axis=1)
# same for np.std, i dont show again here

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


array([10, 15, 20, 25, 30, 35])

In [19]:
def cal_volume(time, name): #_v is price #function used for calculating volume within time intervals
    get_all_shifted_2Darray= np.lib.stride_tricks.sliding_window_view(asc_v_np, time) #hard to explain, just see the above cell and output #btw, i show this in presentation already
    sumed = np.sum(get_all_shifted_2Darray ,axis=1) #sum elements in each inner array
    return pd.DataFrame({'volume '+name : sumed}) #return df

In [20]:
#put together

# ~5sec
volume_df = pd.concat( #concat everything of the volume part
    [
    cal_volume(_1m,'1m'),
    cal_volume(_10m,'10m'),
    cal_volume(_30m,'30m'),
    cal_volume(_1h,'1h'),
    cal_volume(_3h,'3h'),
    cal_volume(_6h,'6h'),
    cal_volume(_12h,'12h'),
    cal_volume(_1d,'1d'),
    ],
    axis=1 #1 means concat along columns
)

no need to add one row, because volume in 1min is not return in 1min, no need to get future data, therefore not all NaN in first row, and no auto remove row will happen

then just do the same thing same as above, except adding rows

In [21]:
# important, check rows
print(volume_df.shape,btc_time_close_volume.shape) 

(2938666, 8) (2938666, 3)


In [22]:
volume_df_back = volume_df[::-1] #reverse back
volume_df_back.reset_index(drop=True, inplace=True) #reset index
volume_df_back.head() #check head

volume 1m  volume 10m  volume 30m  volume 1h  volume 3h  volume 6h  \
0   0.107347         NaN         NaN        NaN        NaN        NaN   
1   2.634666         NaN         NaN        NaN        NaN        NaN   
2   1.128569         NaN         NaN        NaN        NaN        NaN   
3   1.401139         NaN         NaN        NaN        NaN        NaN   
4   0.026117         NaN         NaN        NaN        NaN        NaN   

   volume 12h  volume 1d  
0         NaN        NaN  
1         NaN        NaN  
2         NaN        NaN  
3         NaN        NaN  
4         NaN        NaN

return + volume part is finished
##### now start volatility(sd of return) of diff time intervals

In [23]:
# # actually everything is the same, just different in getting
asc_r_1m_arr=np.array(returns_df_back['return% 1m'])[::-1] #reverse the time order, more readable, asc = ascending

def cal_volat(time, name): #function used for calculating volume within time intervals #time is what interval you want, name is the column name
    get_all_shifted_2Darray= np.lib.stride_tricks.sliding_window_view(asc_r_1m_arr, time) #same as the way we do for volume
    stded = np.std(get_all_shifted_2Darray ,axis=1) #we use std, because we want to get the sd within a time interval
    return pd.DataFrame({'volat '+name : stded}) #return df

now we will run the function in different time intervals.

i chose to run them separately because i can see which part use how much time.

In [24]:
sd1m = cal_volat(_1m,'1m')

In [25]:
sd10m = cal_volat(_10m,'10m')

In [26]:
sd30m = cal_volat(_30m,'30m')

need to be <mark style="background-color: yellow">VERY BECAREFUL WHEN RUNNING BELOW CELLS</mark>

the below number are time my computer needs (i7 + 32RAM + x64), may cause more time depends on your spec

sd1h=4s
sd3h=6s
sd6h=10+s
sd12h=20s
sd1d=15m+

PPPPS: one of our groupmates used 16GBram to do sd12h, and takes >>20min

In [27]:
sd1h = cal_volat(_1h,'1h')

In [28]:
sd3h = cal_volat(_3h,'3h')

In [29]:
sd6h = cal_volat(_6h,'6h')

In [30]:
sd12h=cal_volat(_12h,'12h')

think before running this if your spec is not good.
took my pc 20mins and not yet finish.

the steps and logic are the same as the above cells, just different in time interval, but since it takes too too long, so our group decided not to do volatility12h

In [31]:
# sd1d=    cal_volat(_1d,'1d')

In [32]:
#put together

# ~5sec
volat_df = pd.concat( #concat everything of the volatility part
    [
    sd1m,
    sd10m,
    sd30m,
    sd1h,
    sd3h,
    sd6h,
    sd12h
    ],
    axis=1 #1 means concat along columns
)

In [33]:
volat_df_back = volat_df[::-1] #reverse back
volat_df_back.reset_index(drop=True, inplace=True) #reset index
volat_df_back.head() #check head5

volat 1m  volat 10m  volat 30m  volat 1h  volat 3h  volat 6h  volat 12h
0       0.0        NaN        NaN       NaN       NaN       NaN        NaN
1       0.0        NaN        NaN       NaN       NaN       NaN        NaN
2       0.0        NaN        NaN       NaN       NaN       NaN        NaN
3       0.0        NaN        NaN       NaN       NaN       NaN        NaN
4       0.0        NaN        NaN       NaN       NaN       NaN        NaN

In [34]:
btc_everything = pd.concat( #concat everything we have done so far
    [btc_time_close_volume_ret,
     volume_df_back,
     volat_df_back
    ],
    axis=1 #1 means concat along columns
)

In [35]:
btc_everything.tail() #just to check

Date   Close    Volume  return% 1m  return% 10m  \
2938661  2015-10-08 13:44:00  242.96  0.033491    0.000000     0.839644   
2938662  2015-10-08 13:43:00  242.96  0.010000    0.000000     0.839644   
2938663  2015-10-08 13:42:00  242.95  0.000000    0.004116     0.843795   
2938664  2015-10-08 13:41:00  242.95  0.001000    0.000000     0.843795   
2938665  2015-10-08 13:40:00  242.50  0.050000    0.185567     1.030928   

         return% 30m  return% 1h  return% 3h  return% 6h  return% 12h  ...  \
2938661     0.633849    0.839644    0.633849    0.428054     0.263418  ...   
2938662     0.633849    0.839644    0.633849    0.428054     0.263418  ...   
2938663     0.637991    0.823215    0.637991    0.432188     0.267545  ...   
2938664     0.637991    0.823215    0.637991    0.432188     0.267545  ...   
2938665     0.824742    1.010309    0.824742    0.618557     0.453608  ...   

         volume 6h  volume 12h  volume 1d  volat 1m  volat 10m  volat 30m  \
2938661  21.054041   34.693703  36.686703       0.0   0.246414   0.153391   
2938662  21.064041   34.703703  36.696703       0.0   0.246414   0.153391   
2938663  21.064041   34.703703  36.696703       0.0   0.246277   0.153374   
2938664  21.065041   34.704703  36.697703       0.0   0.246277   0.153374   
2938665  21.115041   34.754703  36.747703       0.0   0.246212   0.156107   

         volat 1h  volat 3h  volat 6h  volat 12h  
2938661  0.114644  0.067315  0.052180   0.038958  
2938662  0.114644  0.067315  0.052180   0.038958  
2938663  0.114648  0.067315  0.052180   0.038959  
2938664  0.114648  0.067315  0.052180   0.038959  
2938665  0.116720  0.068660  0.053075   0.039564  

[5 rows x 26 columns]

In [36]:
# save
#takes >1.5min because the file is really big
btc_everything.to_csv('btc_everything.csv')